Feature/#17 dashboard
racketometer/frontend-application pull request #27
Opened 2016-10-21 11:32 UTC by Crevil

2016-10-21 12:03 UTC, Karnich requested changes

2016-10-21 12:03 UTC, Karnich commented on app/base-view/base-view.component.html
> +</GridLayout>
oh crap. need newline

2016-10-21 12:03 UTC, Karnich commented on app/base-view/base-view.component.ts
> +
alot of linesspaces used for nothing? maybe remove 1 or 2?

2016-10-21 12:03 UTC, Karnich commented on app/base-view/tabs/tab/tab.component.html
> +</StackLayout>
newline

2016-10-21 12:03 UTC, Karnich commented on app/base-view/tabs/tabs.component.html
> +</GridLayout>
newline

2016-10-21 12:03 UTC, Karnich commented on app/bluetooth-details/bluetooth-details.component.ts
>      // TODO: Route someplace?
remove todo comment when you added routing

2016-10-21 12:03 UTC, Karnich commented on app/bluetooth/bluetooth.component.html
> +</rom-base-view>
newline

2016-10-21 12:03 UTC, Karnich commented on app/bluetooth/bluetooth.component.html
> +					<Label [text]='item.name'></Label>
this file have some crazy indent/spacing going on

2016-10-21 12:03 UTC, Karnich commented on app/bluetooth/bluetooth.component.ts
> +          .then(() => this.router.navigate(["dashboard"]));
you dont need to reroute because BLE is not enabled?

2016-10-21 12:03 UTC, Karnich commented on app/dashboard/dashboard.component.html
> +</rom-base-view>
newline

2016-10-21 12:03 UTC, Karnich commented on app/dashboard/tile/tile.component.html
> +</StackLayout>
newline

2016-10-21 12:03 UTC, Karnich commented on app/login/login.component.html
> +</rom-base-view>
newline

2016-10-21 12:03 UTC, Karnich commented on app/started-sessions/started-sessions.component.html
> +</rom-base-view>
newline

2016-10-22 16:02 UTC, Crevil commented on app/bluetooth/bluetooth.component.ts
> +          .then(() => this.router.navigate(["dashboard"]));
Left over for demo flow. Removing.

2016-10-22 16:05 UTC, Crevil commented
@Karnich I've made the changes you requested. Good catches.

2016-10-23 20:39 UTC, merged